### ISSUE TITLE
Building structures as marine is broken

### ISSUE THREAD

**Issue by Laaas** [MysteriousMilk/NS2_CombatPlusPlus#30]
There are several problems:
After you select a building to construct, you can never select a building again.
You will not be able to reselect the builder tool after unselecting it.
Each time you respawn, the builder tool will be reselected automatically.
You can build no matter how many skill points you have, i.e. you can reach reach negative skill points.
You do not regain your skill points when a structure is destroyed.

**Comment by MysteriousMilk** [comment]
Every thing should be working now.  Still no good way to reselect the builder (create mode).  That will take some more thinking on a good design approach for that.

**Comment by Laaas** [comment]
You can just make the builder a selectable weapon

**Comment by MysteriousMilk** [comment]
Can you have more than 5 selectable weapons in ns2?  Supposing you can, this would work.  Only make it selectable when you have a purchased structure queued up.

**Comment by Laaas** [comment]
This is a bad solution now that I think about it, just have players reselect the building in the buy menu

**Comment by MysteriousMilk** [comment]
Most of the time, the player is not going to unselect the builder unless they are under attack.  Cost doesn't get deducted until the structure is actually placed.  So I think it's fine for them to go back to the buy menu and select again.

**Comment by Laaas** [comment]
btw you need to enable sprinting while builder is out

**Comment by MysteriousMilk** [comment]
Ok I'll look into that. Drop an issue on the backlog so I don't forget.
