### ISSUE TITLE
Alien Buy Menu completely broken

### ISSUE THREAD

**Issue by Laaas** [MysteriousMilk/NS2_CombatPlusPlus#32]
I am not exactly sure what the problems are

**Comment by MysteriousMilk** [comment]
The issues that were broken in the first playtest have been corrected.  You should now be able to:
- [x] Buy upgrades as a skulk
- [x] Upgrade to a new lifeform
- [x] Purchase ability upgrades for your current lifeform (or lifeform you are evolving to)
- [x] Should be able to a new a new lifeform, with upgrades and new abilities all at once.
