### ISSUE TITLE
Mod crashes server with too many entities error

### ISSUE THREAD

**Issue by Laaas** [MysteriousMilk/NS2_CombatPlusPlus#41]
Compressed log file: [log.txt.gz](https://github.com/MysteriousMilk/NS2_CombatPlusPlus/files/2042583/log.txt.gz)

Mods on the server:
- [Flame Sentries](https://github.com/woozasmoddingteam/FlameSentry)
- Wooza's Potpourri
- Shine Administration
- Lua Configuration
- NS2+
- NS2 Optimizations
- Smarter MAC

This happened on ns2_co_biodome, just a minute after changing to it.
There were no errors prior to this.

**Comment by MysteriousMilk** [comment]
I introduced this bug in my last publish.  It's fixed in my feature branch.  I'll hopefully get it published here in the next day or so.

**Comment by MysteriousMilk** [comment]
Should be fixed now.
