### ISSUE TITLE
Does not work when client and server platforms aren't the same

### ISSUE THREAD

**Issue by Laaas** [MysteriousMilk/NS2_CombatPlusPlus#42]
Linux server and Linux client works fine, but Windows server and Linux client doesn't.
Windows server and Windows client also works fine.

I suspect this is due to case-insensitivity.

**Comment by Laaas** [comment]
I also get `[  9.735] MainThread : Error: File 'game_setup.xml' failed consistency check!`

**Comment by MysteriousMilk** [comment]
I'm currently changing my file hooks over to the folder style used in Combat Classic.  Hopefully that will fix it.  I won't have a Linux client to test though.  I also realized I hooked CPPMarineHUD.lua twice.  One was located with the same path structure as vanilla and one was not.  They both had different code in it. I moved it to one file in my working branch.  With the game_settings.xml, could it be that I didn't have all the tags in it?  That's been corrected in my working branch as well.
